// Generated by CoffeeScript 1.5.0
(function() {
  var x;

  console.log(((function() {
    var _i, _results;
    _results = [];
    for (x = _i = 1; _i < 1000; x = ++_i) {
      if (x % 3 === 0 || x % 5 === 0) {
        _results.push(x);
      }
    }
    return _results;
  })()).reduce(function(i, m) {
    return i + m;
  }));

}).call(this);
