// Generated by CoffeeScript 1.5.0
var fib, fib2, ret, _i, _results;

fib = function(n) {
  if (n < 2) {
    return n;
  } else {
    return fib(n - 1) + fib(n - 2);
  }
};

fib2 = function(n) {
  var add, first, i, second, _i;
  for (i = _i = 0; 0 <= n ? _i <= n : _i >= n; i = 0 <= n ? ++_i : --_i) {
    if (i === 0) {
      first = 1;
      second = 0;
    } else {
      add = first + second;
      first = second;
      second = add;
    }
  }
  return add;
};

ret = (function() {
  _results = [];
  for (_i = 1; _i <= 40; _i++){ _results.push(_i); }
  return _results;
}).apply(this).map(function(n) {
  return fib2(n);
}).filter(function(n) {
  return n < 4000000;
}).filter(function(n) {
  return n % 2 === 0;
}).reduce(function(memo, i) {
  return memo + i;
});

console.log(ret);
